import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useNestore from '../store'


const Hello = () => {
  const [value, setValue] = useNestore('hello')

  
  return(
    <div className='nestore-container' >
      <p suppressHydrationWarning={true}>hello: {value}</p>
      <button onClick={()=>setValue('friends')}>friends</button>
      <button onClick={()=>setValue('people')}>people</button>
      <button onClick={()=>setValue('yall')}>yall</button>
    </div>
  )

}

const Count = () => {
  const [value, setValue] = useNestore('count')
  
  return(
    <div className='nestore-container'>
      <p suppressHydrationWarning={true}>count: {value}</p>
      <button onClick={()=>setValue(0)}>0</button>
      <button onClick={()=>setValue(1)}>1</button>
      <button onClick={()=>setValue(2)}>2</button>
    </div>
  )

}

const Time = () => {
  const [value, setValue] = useNestore('time')
  
  return(
    <div className='nestore-container'>
      <p suppressHydrationWarning={true}>time: {value}</p>
      <button onClick={()=>setValue(Date.now())}>now</button>
    </div>
  )

}


const Store = () => {
  const [value, setValue] = useNestore()
  
  return(
    <div className='nestore-container'>
      <pre suppressHydrationWarning={true}>{JSON.stringify(value, null, 2)}</pre>
      <button onClick={()=>setValue({hello: 'World!', count: 0, time: Date.now()})}>reset</button>
    </div>
  )

}


const PersonName = () => {
  const [value, setValue] = useNestore('person.name')
  
  return(
    <div className='nestore-container'>
      <p suppressHydrationWarning={true}>person.name: {value}</p>
      <button onClick={()=>setValue('Alice')}>Alice</button>
      <button onClick={()=>setValue('Bob')}>Bob</button>
      <button onClick={()=>setValue('Charles')}>Charles</button>
    </div>
  )

}


const PersonAge = () => {
  const [value, setValue] = useNestore('person.age')
  
  return(
    <div className='nestore-container'>
      <p suppressHydrationWarning={true}>person.age: {value}</p>
      <button onClick={()=>setValue(30)}>30</button>
      <button onClick={()=>setValue(40)}>40</button>
      <button onClick={()=>setValue(50)}>50</button>
    </div>
  )

}


const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nestore hook test <a href="https://nextjs.org">Next.js</a>
        </h1>

        <button onClick={() => window?.localStorage?.removeItem('my-store-key')}>Clear Storage</button>
        
        <Hello />
        <Count />
        <Time />
        <PersonName />
        <PersonAge />
        <Store />

      </main>
    </div>
  )
}

export default Home
